executable = /bin/bash
arguments  = /fast/jtaraz/LIARS/colosseum-detection/cluster/run_rejudge7.sh
error  = /fast/jtaraz/LIARS/colosseum-detection/cluster/rejudge7_$(Cluster).err
output = /fast/jtaraz/LIARS/colosseum-detection/cluster/rejudge7_$(Cluster).out
log    = /fast/jtaraz/LIARS/colosseum-detection/cluster/rejudge7_$(Cluster).log
request_gpus   = 0
request_cpus   = 4
request_memory = 8192
request_disk   = 2G
+BypassLXCfs   = "true"
queue 1
